### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by binhgo** [fulldecent/system-bus-radio#47]
Hi Pro,

Do you know how to catch analog signals using wifi card on macOS?

What I want to do is to catch the raw analog signals from the wifi card or something like that and write the data down, might be in the form of binary 1s and 0s.

As I know that wifi router will emit/receive EM waves and wifi card on laptop also receive/emit that EM waves. So just want to know how the analog data is.

Thanks.

**Comment by fulldecent** [comment]
Hello Binh,

I think you are looking for Software Defined Radio. Here is a good place to start your studies -- https://www.rtl-sdr.com. Sorry I have not used this myself and cannot provide support for using that. 

But I'll leave this issue open for a bit because I think you might get a better answer here...

**Comment by binhgo** [comment]
Thanks Fulldecent,

Let me check that link.
Because I think that in our laptop, there is a Wifi card to "catch" the analog/digital signal (EM waves) from Wifi router or Access point, so that there must be some low level code to access these signal like the Operating System is doing and then decode these analog/digital signal into binary 1s and 0s.

**Comment by fulldecent** [comment]
The Wi-Fi receiver does not allow such low-level access to catch 0's and 1's at the physical level. Only specialized hardware like SDR will allow that.
